name: Code Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build SFTPGo
      run: go build -i -ldflags "-s -w -X github.com/drakkan/sftpgo/version.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/version.date=`date -u +%FT%TZ`" -o sftpgo

    - name: Upload sftpgo executable
      uses: actions/upload-artifact@v2
      with:
        name: sftpgo-build
        path: sftpgo

    - name: Upload templates
      uses: actions/upload-artifact@v2
      with:
        name: sftpgo-build
        path: templates

    - name: Upload static files
      uses: actions/upload-artifact@v2
      with:
        name: sftpgo-build
        path: static
